name: Build and Run F# Programs

on:
  push:
    branches:
      - feature/emin  # Adjust the branch name as needed

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Adjust to the desired .NET version

      - name: Build Server and Client
        run: |
          dotnet build Server/Server.fsproj
          dotnet build Client/Client.fsproj

      - name: Run Server and Client in Parallel
        run: |
          timeout -t 10s dotnet run --project Server/Server.fsproj &
          timeout -t 10s dotnet run --project Client/Client.fsproj &