name: Build and Run F# Programs

on:
  push:
    branches:
      - feature/emin  # Adjust the branch name as needed

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        configuration:
          - project: "Server/Server.fsproj"
          - project: "Client/Client.fsproj"
          # Add more configurations as needed

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Adjust to the desired .NET version

      - name: Build Project
        run: |
          dotnet build ${{ matrix.configuration.project }}

      - name: Run Project
        timeout-minutes: 1  # Set the maximum duration for the step to 1 min
        run: |
         if [[ "${{ matrix.configuration.project }}" == "Client/Client.fsproj" ]]; then
            echo "Waiting for 10 seconds..."
            sleep 30
          fi
          dotnet run --project ${{ matrix.configuration.project }}
