name: Build and Run F# Programs

on:
  push:
    branches: '**'

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Adjust to the desired .NET version

      - name: Build Server
        run: |
          dotnet build Server/Server.fsproj
      - name: Build Client
        run: |
          dotnet build Client/Client.fsproj
      - name:  Run Server and client
        timeout-minutes: 1
        run: |
          # Build the server and run it in the background
          dotnet run --project Server/Server.fsproj &

          # Build the client and run it in the background
          dotnet run --project Client/Client.fsproj
